# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -f spworlds-csharp-library.sln
    - name: Build
      run: dotnet build spworlds-csharp-library.sln --configuration Release --no-restore 
    - name: Test
      run: dotnet test spworlds-csharp-library.sln --no-build --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with: 
        PROJECT_FILE_PATH: spworlds.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
      
